# fly.toml app configuration file generated for recipes-elr on 2023-07-20T18:31:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "recipes-elr"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "mad"
processes = []

[build]
  dockerfile = "docker/dockerfile"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
